### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by BorisBrock** [anoved/OctoPrint-EmailNotifier#48]
No updates in a long time. Also it does not show up in the Octoprint plugin repository :-(

**Comment by anoved** [comment]
Correct. I can no longer maintain it (keeping up with OctoPrint API changes and implementing needed features was beyond my abilities). I removed it from the public repository because I was receiving many complaints about installation difficulties that I was unable to resolve, and I felt bad about disappointing people who expected a polished plug-in. It was an experiment that worked for me, but getting it to work for everyone else just proved to be a source of stress.

I invite you or anyone else to fork and fix it! You are welcome to publish your own fork in the repository.
